config/routes.rb
Moviescatalog::Application.routes.draw do

  devise_for :users

  root :to => "movies#index"
  get 'contributor' => 'movies#contributor'
  get 'tags/:tag', to: 'movies#index', as: :tag

  resources :movies do
      resources :comments, :only => [:create, :destroy], :belongs_to => :movie
      post :vote_up_down, {:controller => :votes, :action => :vote_up_down}

      member do
        get :tag_edit, {:action => :tag_edit}
        patch :tag_update, {:action => :tag_update}
      end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

    def tag_edit
        @movie = Movie.find(params[:id])

        if params[:checked_tags].present?
            Movie.new.tag_update(@movie, '', params[:checked_tags])
        end

        @tags_already_checked = @movie.tag_list

        if params[:q].present?
            ajax_similar_tags_search = Movie.where("match(movie_title, contributor, contributor_comment) against(\"#{params[:q]}\")").map{|m| m.tag_list}.flatten.uniq
            @recommended_tags = (ajax_similar_tags_search - @tags_already_checked)
        else
            tag_ids = MoviesTags.where(:movie_id => params[:id]).map{|a| a.tag_id}
            recommended_tags_all = Movie.tag_counts_on(:tags).select{|x| tag_ids.include?(x.id)}.inject([]){|y, z| y << z.name ;y}
            @recommended_tags = (recommended_tags_all - @tags_already_checked)
        end

        respond_to do |format|
            format.html
            format.js
        end
    end

    def tag_update
        @movie = Movie.find(params[:id])

        respond_to do |format|
            if Movie.new.tag_update(@movie, params[:tag_list], params[:tag_check_box_list])
                format.html { redirect_to @movie, notice: "動画タグのデータベースへの登録に成功しました" }
            else
                format.html { redirect_to tag_edit_movie_path, alert: "動画タグのデータベースへの登録に失敗しました。再度入力してみてください" }
            end
        end
    end


  def contributor
    @movies = Movie.where(:contributor => current_user.contributor).page(params[:page])
  end


  # GET /movies
  # GET /movies.json
  def index
    if params[:search_query].present?
        @movies = Movie.new.movies_search(
                                params[:search_query],
                                params[:search_column],
                                params[:search_result_sort],
                                params[:page]
                                )
    elsif params[:tag].present?
        @movies = Movie.tagged_with(params[:tag]).page(params[:page])
    else
        @movies = Movie.page(params[:page])
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    next_play_counts = set_movie.play_counts += 1
    set_movie.update(:play_counts => next_play_counts)

    @movies = Movie.page(params[:page])

    @movie = Movie.find(params[:id])

    @vote = Vote.new.vote_like_dislike_count(@movie, current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit

  end


  # POST /movies
  # POST /movies.json
  def create
    respond_to do |format|
      if upload_movie_info = Movie.new.upload_movie_extract_info_and_save(params[:movie][:upfile], current_user)
            @movie = Movie.new(movie_params.merge!(upload_movie_info))

            if @movie.save
              MoviesTags.new.tag_recommend_database
              Movie.new.movie_thumbnails_create(File.join(Rails.root, upload_movie_info[:local_file_path]))
              format.html { redirect_to @movie, :notice => "#{@movie.file_basename}のアップロードに成功しました"}
              format.json { render action: 'show', status: :created, location: @movie }
            else
              flash[:notice]="動画メタデータのデータベースへの登録に失敗しました。再度実行してください"
              format.html { render action: 'new' }
              format.json { render json: @movie.errors, status: :unprocessable_entity }
            end
      else
        flash[:notice]="動画ファイルが指定されていないか、アップロードされたファイルは動画ではありません。再度動画ファイルを指定して実行してください"
        @movie = Movie.new(movie_params)
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        MoviesTags.new.tag_recommend_database
        format.html { redirect_to @movie, notice: "動画メタデータのデータベースへの登録に成功しました" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    Movie.new.movie_and_thumbnails_destroy(File.join(Rails.root, @movie.local_file_path))
    MoviesTags.new.tag_recommend_database
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end


  private

    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:file_name, :local_file_path, :file_basename, :movie_title, :contributor, :contributor_comment, :play_counts, :size, :path, :duration, :creation_time, :bitrate, :video_codec, :colorspace, :video_bitrate, :resolution, :audio_codec, :audio_channels, :audio_bitrate, :audio_sample_rate,
            :tag_list, :tag_check_box_list
            )
    end


end

app/helpers/movies_helper.rb
module MoviesHelper

end

app/views/movies/_movieplay.html.erb
<%= video_tag(URI.escape("/videos/#{@movie.file_name}"), :width => 550, :controls => true, :autobuffer => false) %>

<table border=0 word-break="break-all" width="540px" cellspacing="8" >
    <tr><th colspan=7 style="color:#4169E1; font-size:18px;"><%= @movie.movie_title %></th></tr>

    <tr><th colspan=7><%= @movie.created_at.strftime("%Y/%m/%d %H:%M:%S") %></th></tr>

    <tr><td style='text-align:right;'>投稿者:</td><th style='text-align:left;'><%= @movie.contributor %></th>
            <td style='text-align:right;'>再生時間:</td><th style='text-align:left;'><%= Movie.new.timespan(@movie.duration) %></th>
            <td style='text-align:right;'>再生回数:</td><th style='text-align:left;'><%= @movie.play_counts %></th></tr>

    <tr><th colspan=7 width="350px">
        <%= raw @movie.tag_list.map { |t| link_to t, tag_path(t),:style=>"color:#006400; font-size:15px;" }.join(' ') %>
    </th></tr>

    <tr ><td colspan=2 style='text-align:right;'>投稿者コメント:</td><th colspan=5 width="350px"><%= @movie.contributor_comment %></th></tr>

    <tr><th colspan=7>
        <% if user_signed_in? %>

            <%= link_to '動画タグ編集', tag_edit_movie_path(@movie), :id=>"movie_edit_link" %>

            <% if (@movie.contributor == current_user.contributor) %>
                <%= link_to '動画情報を編集', edit_movie_path(@movie), :id=>"movie_edit_link" %>
                <%= link_to '動画を削除', movie_path(@movie), {:confirm=>"動画を削除してもよろしいですか？", :method=>:delete, :id=>"movie_edit_link"} %>
            <% end %>

        <% end %>
    </th></tr>

</table>

app/views/movies/_movieslist.html.erb
<% if turnning %>
    <% rowcol = 'colspan=9' %>
    <% newline = '</tr><tr>' %>
<% else %>
    <% rowcol = 'rowspan=4' %>
    <% newline = '' %>
<% end %>


<% movies.each do |movieslist| %>
    <table border=0 style="word-break: break-all;">
        <tr><td width="580" <%= rowcol %>>
                <div style="position: relative;">
                        <% 5.times do |thumbnails_count| %>
                        <%= link_to image_tag(URI.escape("/images/thumbnails/#{File.basename(movieslist.file_name, '.mp4')}_#{thumbnails_count}.jpg"), :width => 110 ), movie_path(movieslist) %>
                        <% end %>

                        <div id="duration" style="position:absolute; top:60px; left:495px; width: 70px;">
                                <%= link_to Movie.new.timespan(movieslist.duration), movie_path(movieslist), {:height=>0} %>
                        </div>
                </div>
                </td>

                <%= raw(newline) %>

                <th colspan=9 width="580" >
                    <%= link_to movieslist.movie_title, movie_path(movieslist),:style=>"color:#4169E1; font-size:16px;" %>
                </th></tr>
        <tr>
                <th><%= movieslist.created_at.strftime("%Y/%m/%d %T") %></th>
                <td style='text-align:right;'>投稿者 : </td><th style='text-align:left;'><%= movieslist.contributor %></th>
                <td style='text-align:right;'>評価 : </td><th style='text-align:left;'><%= movieslist.rating %></th>
                <td style='text-align:right;'>再生回数 : </td><th style='text-align:left;'><%= movieslist.play_counts %></th>
        </tr>

        <tr><th colspan=9 width="580" style="color:#808080; font-size:12px;">
            <%= truncate(movieslist.contributor_comment, {:length => 45}) %>
        </th></tr>

        <tr><th colspan=9 width="580">
            <%= raw movieslist.tag_list.sort!.map { |t| link_to t, tag_path(t),:style=>"color:#006400; font-size:13px;" }.join(' ') %>
        </th></tr>

    </table>
    <hr>
<% end %>

app/views/movies/_movieslist_pagination.html.erb
<%= render :partial => 'movies/movieslist', :locals => {:movies => movies, :turnning => turnning} %>


<div id="view_more">
    <b>
    <%= movies.total_count %>件中
    <%= 1 %>〜<%= movies.offset_value + movies.length %>件を表示しています。
    </b>
    <br>

    <% unless movies.last_page? %>
        <%= link_to(image_tag(URI.escape("/images/more_movies_arrow.png"), :width => 250),
            {:url => movies_path,
            :search_query => params[:search_query],
            :search_column => params[:search_column],
            :search_result_sort => params[:search_result_sort],
            :page => movies.next_page},
            {:remote => true,
            :id => 'kaminari_next_page',
            data: {disable_with: 'loading...'}
            }
            ) %>
    <% end %>
</div>

app/views/movies/_tag_edit_tag_group_box.html.erb
<div class="wrap">
      <% tags_grouping.each do |x| %>
        <div class="box">
        <div class="field">
        <label>
            <%= x %><%= check_box_tag "tag_check_box_list[]", "#{x}", check_true_false, :id => 'tag_check_box' %>
        </label>
        </div>
        </div>
      <% end %>
</div>

app/views/movies/contributor.html.erb
<table border="0" width="100%">
<tr><td width="510px" valign="top">

    <h2>あなたのユーザープロフィール</h2>
    <table border="0" style="margin: 0 auto;" >
    <tr><th>ユーザー名</th><td><%= current_user.contributor %></td></tr>
    <tr><th>メールアドレス</th><td><%= current_user.email %></td></tr>
    <tr><th>ユーザー登録した日時</th><td><%= current_user.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td></tr>
    <tr><th>あなたの投稿した動画数</th><td><%= @movies.total_count %></td></tr>

    <tr><th>今回ログインした日時</th><td><%= current_user.current_sign_in_at.strftime("%Y/%m/%d %H:%M:%S") %></td></tr>
    <tr><th>前回ログインした日時</th><td><%= current_user.last_sign_in_at.strftime("%Y/%m/%d %H:%M:%S") %></td></tr>
    </table>

    <%= link_to 'ユーザープロフィール変更', edit_user_registration_path %>




</td><td width="20px" valign="top"></td>
<td width="590px" valign="top">

    <h2>あなたの投稿した動画</h2>
    <%= render :partial => 'movies/movieslist_pagination', :locals => {:movies => @movies, :turnning => true} %>

</td></tr>
</table>

app/views/movies/contributor.js.erb
$("#view_more").replaceWith("<%= escape_javascript(
    render :partial => 'movies/movieslist_pagination', :locals => {:movies => @movies, :turnning => true}
    )%>");


$(window).on("scroll", function() {
var scrollHeight = $(document).height();
var scrollPosition = $(window).height() + $(window).scrollTop();
if ((scrollHeight - scrollPosition) / scrollHeight === 0) {

        $('#kaminari_next_page').trigger('click');
        //alert("スクロールしました");
        sleep(100);
}
});

app/views/movies/edit.html.erb
<h1>動画情報変更</h1>

<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_title %>(10~100文字以内にしてください)<br>
    <%= f.text_field :movie_title, {:size => 100} %>
  </div>
  <div class="field">
    <%= f.label :contributor_comment %>(空欄でもかまいません)<br>
    <%= f.text_area :contributor_comment, {:size => "70x10"} %>
  </div>
  <div class="actions">
    <%= f.submit '動画ファイルアップロード', :disable_with=>'アップロード処理中...' %>
  </div>
<% end %>


<%= link_to 'Back', movie_path(@movie) %>

app/views/movies/index.html.erb
<%= render :partial => 'movies/movieslist_pagination', :locals => {:movies => @movies, :turnning => false} %>

app/views/movies/index.js.erb
//alert("クリックしました");
$('#view_more').replaceWith("<%= escape_javascript(
    render :partial => 'movies/movieslist_pagination', :locals => {:movies => @movies, :turnning => false}
    )%>");


$(window).on("scroll", function() {
var scrollHeight = $(document).height();
var scrollPosition = $(window).height() + $(window).scrollTop();
if ((scrollHeight - scrollPosition) / scrollHeight === 0) {

        $('#kaminari_next_page').trigger('click');
        //alert("スクロールしました");
        sleep(100);

}
});

app/views/movies/new.html.erb
<h1>動画投稿</h1>

<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label "動画ファイルを指定してください" %><br />
    <%= f.file_field "upfile", {:size => 50} %>
  </div>
  <div class="field">
    <%= f.label :movie_title %>(10~100文字以内にしてください)<br>
    <%= f.text_field :movie_title, {:size => 100} %>
  </div>
  <div class="field">
    <%= f.label :contributor_comment %>(空欄でもかまいません)<br>
    <%= f.text_area :contributor_comment, {:size => "70x10"} %>
  </div>
  <div class="actions">
    (アップロードには50MBで10分以上かかることがあります)
    <%= f.submit '動画ファイルアップロード', :disable_with=>'アップロード処理中...' %>
  </div>
<% end %>



<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<table border="0" width="100%">
<tr><td width="510px" valign="top">

    <%= render 'movies/movieplay',:locals => {:movie=> @movie, :tags => @tags} %>


    <%= render :partial => "votes/vote_status", :locals => {:movie => @movie, :vote => @vote} %>

    <%=render :partial => 'comments/index',:locals => {:commentable=> @movie, :comments => @comments} %>
    <%= render :partial => "comments/new", :locals => {:commentable => @movie} %>

</td>
<td width="20px" valign="top"></td>
<td width="590px" valign="top">

    <%= render :partial => 'movies/movieslist_pagination', :locals => {:movies => @movies, :turnning => true} %>

</td></tr>
</table>

app/views/movies/show.js.erb
$("#view_more").replaceWith("<%= escape_javascript(
    render :partial => 'movies/movieslist_pagination', :locals => {:movies => @movies, :turnning => true}
    )%>");


$(window).on("scroll", function() {
var scrollHeight = $(document).height();
var scrollPosition = $(window).height() + $(window).scrollTop();
if ((scrollHeight - scrollPosition) / scrollHeight === 0) {

        $('#kaminari_next_page').trigger('click');
        //alert("スクロールしました");
        sleep(100);
}
});

app/views/movies/tag_edit.html.erb
<%= javascript_include_tag 'application' %>
<h1>動画タグ編集</h1>

<hr>
<%= render :partial => 'movies/movieslist', :locals => {:movies => [@movie], :turnning => false} %>


<%= form_tag({:controller => "movies", :action => "tag_update"}, {:id => "tag_edit_form", :method => :patch, :ajax_path => tag_edit_movie_path(@movie)}) do %>

    <h2>新規のタグを追加</h2>
        Tags (複数のタグはスペースで区切ること)
        <%= text_field_tag :tag_list, '', :id=>'search_tag_word' %>


    <h2>他の動画のタグからの推奨タグ検索</h2>
    <div id='ajax_tag_update'>
    <%= render(:partial => 'movies/tag_edit_tag_group_box', :locals => {:tags_grouping => @recommended_tags, :check_true_false => false}) %>
    </div>


    <h2>すでに付けられているタグ</h2>
    <div id='ajax_already_attached_tag'>
    <%= render(:partial => 'movies/tag_edit_tag_group_box', :locals => {:tags_grouping => @tags_already_checked, :check_true_false => true}) %>
    </div>


    <br>
    <%= submit_tag 'タグ編集', data: { disable_with: 'タグ編集処理中...' } %>

<% end %>



<%= link_to 'Back', movie_path(@movie) %>

app/views/movies/tag_edit.js.erb
//alert("クリックしました");
$('#ajax_tag_update').html("<%= escape_javascript(
    render(:partial => 'movies/tag_edit_tag_group_box', :locals => {:tags_grouping => @recommended_tags, :check_true_false => false})
    )%>");

$('#ajax_already_attached_tag').html("<%= escape_javascript(
    render(:partial => 'movies/tag_edit_tag_group_box', :locals => {:tags_grouping => @tags_already_checked, :check_true_false => true})
    )%>");